Fix setup: don't use requirements.txt
Installing nece in a project results with the following error:
>>> FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'

Instead of setup.py relying on requiremnts.txt, the opposite should be done.
See https://caremad.io/posts/2013/07/setup-vs-requirement/